version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    volumes:
      - type: bind
        source: ../data
        target: /home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.py --NotebookApp.token="
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  mysql_data:
  postgres_data:
